Euclidean spaces : exercises 
======

Implement the following functions with `numpy`

In [8]:
import numpy as np


def norm(x):
    """
    Args:
      x (np.array): vector
    Returns:
      float. the norm of x
    """
    ### BEGIN SOLUTION
    return np.sqrt(x @ x)
    ### END SOLUTION

def distance(x,y):
    """
    Args:
       x (np.array): vector
       y (np.array): vector
    Returns:
       float. the euclidean distance between x and y 
    """
    ### BEGIN SOLUTION
    return norm(x-y)
    ### END SOLUTION

def similarity(x,y):
    """
    Args:
       x (np.array): vector
       y (np.array): vector
    Returns:
	float. the cosine of the angle between x and y
    """
    ### BEGIN SOLUTION
    return (x @ y) / (norm(x) * norm(y))
    ### END SOLUTION

def is_orthogonal(x,y):
    """
    Args:
       x (np.array): vector
       y (np.array): vector
    Returns:
	bool. True if x and y are orthogonal, False otherwise. 
    """
    ### BEGIN SOLUTION
    return similarity(x,y) == 0
    ### END SOLUTION


Euclidean spaces
====

Use numpy or the functions you defined above to solve the following exercises.
Check manually that your solutions are correct.

In [9]:
# Vectors and distances

x = np.array([-1,5,2])
y = np.array([3,1,1])

# Compute x + y
### BEGIN SOLUTION
print(x+y)
### END SOLUTION

# Compute x - y
### BEGIN SOLUTION
print(x-y)
### END SOLUTION

# Compute x / ||x||
### BEGIN SOLUTION
print(x/norm(x))
### END SOLUTION

# Compute || 0.5(x-y)||
### BEGIN SOLUTION
print( norm(0.5*(x-y)))
### END SOLUTION

# Compute || 0.5(x+y)||
### BEGIN SOLUTION
print(x+y)
### END SOLUTION

# Compute x - 2y
### BEGIN SOLUTION
print(x-2*y)
### END SOLUTION

# Does || x-y || = ||x|| - ||y|| ?
### BEGIN SOLUTION
print( norm(x-y) == norm(x) - norm(y) )
### END SOLUTION


# Does || x+y || = ||x|| + ||y|| ?
### BEGIN SOLUTION
print( norm(x+y) == norm(x) + norm(y) )
### END SOLUTION


[2 6 3]
[-4  4  1]
[-0.18257419  0.91287093  0.36514837]
2.8722813232690143
[2 6 3]
[-7  3  0]
False
False


In [14]:
# Angles

#Compute the angle (in degrees) between x and y

x = np.array([5,1,-2])
y = np.array([4,-4,3])

### BEGIN SOLUTION
np.degrees(np.arccos(similarity(x,y)))
### END SOLUTION

#Compute the angle (in degrees) between x and y
x = np.array([7,2,-10])
y = np.array([2,6,4])

### BEGIN SOLUTION
np.degrees(np.arccos(similarity(x,y)))
### END SOLUTION


#Are x and y orthogonal ?

x = np.array([8,4,3])
y = np.array([-2,1,4])

### BEGIN SOLUTION
print('orth',similarity(x,y) == 0)
### END SOLUTION

#Are x and y orthogonal ?

x = np.array([6,0,4])
y = np.array([0,2,-1])

### BEGIN SOLUTION
print('orth',similarity(x,y) == 0)
### END SOLUTION

# Check Cauchy Schwarz is  true on the example:
x = np.array([2,1,4])
y = np.array([1,-2,0])

### BEGIN SOLUTION
print('Cauchy Schwarz', np.abs(x @ y) <= norm(x) * norm(y) )
### END SOLUTION

#Also check that the triangle inequality is true
### BEGIN SOLUTION
print('Triangle', norm(x + y) <= norm(x) + norm(y) )
### END SOLUTION

# Check Cauchy Schwarz is  true on the example:
x = np.array([4,2,-1])
y = np.array([8,4,-2])

### BEGIN SOLUTION
print("Cauchy Schwarz",np.abs(x @ y) <= norm(x) * norm(y))
### END SOLUTION

#Also check that the triangle inequality is true
### BEGIN SOLUTION
print('Triangle',norm(x + y) <= norm(x) + norm(y))
### END SOLUTION


orth True
orth False
Cauchy Schwarz True
Triangle True
Cauchy Schwarz True
Triangle True
